### PR TITLE
feature branch: multi drip lists

### PR DESCRIPTION
**Pull request by efstajas**
https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/%F0%9F%92%A7-Drips?type=design&node-id=3938%3A9644&mode=design&t=iIZX0ox2PnvqK1Vb-1

### CODE REVIEW

**Comment by efstajas** [comment]
@evvvritt any idea what broke tooltips on lists in this PR? 🤔 

Screenshot 2023-10-19 at 16 29 32

**Comment by evvvritt** [comment]
Not immediately no. Do we need Tooltips there? Could we just directly link to profiles/project/drip-list pages?

**Comment by efstajas** [comment]
It's already linking directly, but I think tooltips are quite useful, yeah. It's the only way you can see the full address of a recipient for example, and copy it without having to navigate to the profile and back. Also allows you to quickly see who's in control of the funds going to a claimed project.

**Comment by efstajas** [comment]
@evvvritt fixed it — problem was that the `transform` on the drip-list-card established a new positioning context, but the tooltips rely on being positioned relative to the viewport.

**Comment by efstajas** [comment]
Todo: remove the half-implementation of #698 (new metadata v3). It's halfway done here, but we're gonna launch this later.

**Pull request merged**
