### PR TITLE
add 'total dripped' counter to landing page using static values (closes #645)

### LINKED ISSUE #645: Add Real-Time $ Value of All Tokens on the Protocol
To be clear, this is the total amount of funds that are in Drips. Not the total amount that has been streamed. The sum of everyone's top ups.

image

### PR DESCRIPTION
**Pull request by evvvritt**
(This PR should replace #725)

Adds "$ XXX,XXX dripped" counter to Landing Page using static values:
- Radworks USDC stream
- Radworks RAD stream
- Octant give

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
Maybe the loading state could be improved? Maybe it could be "Loading total dripped amount" or just be invisible until the total dripped amount has loaded and then just fade in? Or maybe it's fine as is. Just ideas…

**Comment by evvvritt** [comment]
Oki, now it fades-in-slides-up when fiat is estimated, wdyt @brandonhaslegs ?

**Comment by efstajas** [comment]
@evvvritt Much nicer but I think a simple fade-in over 300ms would look a lot less jarring!

**Comment by evvvritt** [comment]
Sure

**Comment by brandonhaslegs** [comment]
Maybe instead of a static drip, it's the droplet animation?

**Comment by evvvritt** [comment]
Also sure 👍

**Review by efstajas — APPROVED** [review]
neat

**Review by brandonhaslegs — APPROVED** [review]
looks great

**Pull request merged**
