### PR TITLE
Fix: Typo error - Changed focuessed to focused (Resolves#658)

### LINKED ISSUE #658: Change focussed to focused
In Settings, focussed should be spelled focused since we use American English.

"When enabled, shows developer-**focussed** extra information on address profiles, project profiles and Drip Lists."

### PR DESCRIPTION
**Pull request by yo-404**
# Resolves #658 

## changes proposed in this PR - 
- changed focussed to focused in settings page

## tested on 
- local build

```diff
- subtitle="When enabled, shows developer-focussed extra information on address profiles, project profiles and Drip Lists."
+ subtitle="When enabled, shows developer-focused extra information on address profiles, project profiles and Drip Lists."

```
---

### CODE REVIEW

**Comment by evvvritt** [comment]
Hi! thanks for your help :)

#654 actually targets a rendered web domain in `social-link.svelte` (not URLs in <a href="..."> which can have trailing slashes.

Also, we have some commit message formatting requirements. Were the requirements not being enforced when you committed locally?

**Comment by yo-404** [comment]
> https://github.com/drips-network/app/issues/654 actually targets a rendered web domain in social-link.svelte (not URLs in <a href="..."> which can have trailing slashes.)

Sorry , my bad .. anyways I ' ll look into it and try to fix the issue in another PR 

> Also, we have some commit message formatting requirements. Were the requirements not being enforced when you committed locally?

I used an extension maybe that's why it didn't enforce it on the commit . Will look into it as well

**Comment by yo-404** [comment]
Sorry for the delay , I'll do it right away 💚

**Comment by efstajas** [comment]
Thanks - squash-merging, so the commitlint error isn't a problem.

**Pull request merged**
