### PR TITLE
make avatars on drip-list-card clickable (closes #644)

### LINKED ISSUE #644: Link "Supported by" avatars to relevant profile pages
Screenshot 2023-09-05 at 11 40 20

More context from Bordumb [here](https://discord.com/channels/1096003917717983252/1148164943791804426/1148164943791804426)

### PR DESCRIPTION
**Pull request by evvvritt**
closes #644

added a big focus-visible:ring to linked IdentityBadge when it's just showing just Avatar

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
Hey @evvvritt  is there a specific test project I can look at this on?

**Comment by evvvritt** [comment]
@brandonhaslegs you can set your network in .env to `1` (mainnet) and load the radworks drip list:
`/app/drip-lists/50330452048867519181028275890986093327647919805766323166158196453514`
I don't think there's a drip list out there with more than 1 supporter right now

could be good to add drip-list-card to the component showcase with filler stuff at some point

**Comment by brandonhaslegs** [comment]
> you can set your network in .env to `1`

@evvvritt Don't know what this means. Where do I find .env?

**Comment by evvvritt** [comment]
@brandonhaslegs you can save-as the `.env.template` as `.env` in the root of your local repo. I think you just need to set:
`PUBLIC_NETWORK=1`
although maybe it defaults to mainnet without a .env anyways

**Review by efstajas — APPROVED** [review]
kewl 👍

**Pull request merged**
