### PR TITLE
fix: added continuous donation to drip list

### PR DESCRIPTION
**Pull request by ashiskumar-1999**
Added the logic in the continuous donation button to allow any users to start a continuous donation to any drip list.

closes: (#983)

### CODE REVIEW

**Comment by ashiskumar-1999** [comment]
Hi @efstajas , I'd like to continue this task. Can you give me details that we're about to change with this new feature?
Also, I have tried to query all the accounts that streaming to the given drip list but it throws an error of `Introspection is disabled on this endpoint. Enable introspection to populate your schema.` on the Apollo server playground. can you help me to find why this is happening?

**Comment by ashiskumar-1999** [comment]
Hi @efstajas ,
I want to continue working on this issue. Before that, I have a question regarding the fetching of all accounts streaming to the drip list except the owner. 

- Is there any backend implementation to fetch all the accounts that stream to the drip list as `continuous donation`?because I have tried to query the accounts but didn't get any fields that take me to fetch the accounts having continuous donations.

**Comment by efstajas** [comment]
Hey @ashiskumar-1999, great to hear!

Streams information is currently not available on the GQL API. Instead, you're going to have to use the `streams.store`. There is a function `fetchAccount`, which loads a particular account into the streams store, and also fetches all accounts streaming to that account. You should be able to call `fetchAccount` with a Drip List ID, and it should just automatically fetch all streams coming in to that account. After calling that function, call `getStreamsForUser` with the Drip List ID, and you should receive all relevant `outgoing` streams.

**Comment by efstajas** [comment]
hey @ashiskumar-1999, sorry but someone from our team took this task on now since it's been near the top of our priorities for a while now. Hope you didn't spend too much time on it, and thanks a lot for your efforts.

**Pull request closed without merging**
