### PR TITLE
Add `windows-latest` to CI

### PR DESCRIPTION
**Pull request by jo-elimu**

### CODE REVIEW

**Comment by jo-elimu** [comment]
> Any specific reason to run svelte-check on macos as well?

Just to make sure the software compiles for developers using different types of operating systems. We should also add support for developers with Windows machines (`windows-latest`), but that will require some more code changes.

**Comment by jo-elimu** [comment]
@efstajas Getting "Container action is only supported on Linux": https://github.com/drips-network/app/actions/runs/8027003698/job/21930386799?pr=998



How do developers on Mac OS typically solve this?

**Comment by efstajas** [comment]
Windows support should be given once #997 is merged.

I don't see how running our GH actions on mac OS in addition to Ubuntu would help ensure cross-platform compatibility of our dev stack. I could see running e.g. E2E tests on Mac OS, but they're executed within a docker container anyway. `svelte-check` is cross-platform and should return the exact same output no matter what platform it's run on — if not, that's a bug with svelte-check, not with our project.

**Comment by efstajas** [comment]
I still don't understand the goal here — what's the benefit of running these actions on multiple different operating systems?

**Comment by efstajas** [comment]
Closing this for now until the above ☝️ is addressed

**Pull request closed without merging**
