### PR TITLE
Update features section (closes #649)

### LINKED ISSUE #649: Update features section
Copy edits from Alexa.

---

**You’re in control**
Your data and funds are yours forever. Drips runs fully on sovereign user-controlled infrastructure.

⬇️

- [ ] **User controlled data**
Full sovereign infrastructure for maximum data security.

---
Drips is entirely open-source, and doesn't charge anything extra on top of network gas fees.

⬇️

- [ ] Free to use beyond covering the cost of gas

---

Use ERC-20 tokens “as is”. No need to wrap them or trust a third party with your tokens.

⬇️

- [ ] No need to wrap them or trust a third party with your tokens.

---

**One contract. One payment graph.**
Drips uses one smart contract for streaming and splitting, enabling effortless and flexible token routing.

⬇️

- [ ] **One contract**
Drips uses one smart contract for streaming and splitting.

---

- [ ] Remove:

One balance for all your streams
Fund multiple streams using one account balance in a single transaction.

---

- [ ] Remove:

Coming soon: Multi-Chain
Available on the most popular EVM networks: Ethereum, Mainnet, Polygon, Optimism.

---

- [ ] Since we're removing 2 of these feature sections, make the whole section just 4 cards across, instead of 3x2.
image

### PR DESCRIPTION
**Pull request by christian-carey**
Update text on the landing page

### CODE REVIEW

**Review by evvvritt — APPROVED** [review]
Thanks for your help!! 💙

**Comment by evvvritt** [comment]
Ah wait sorry, can you please update your commit messages to our [required formatting](https://github.com/conventional-changelog/commitlint/#what-is-commitlint) (Does it not flag when you try to commit locally?)

Also, please remove the unused CSS indicated when running `npm run check`

**Review by evvvritt — CHANGES_REQUESTED** [review]
(see prev comment in the PR on required changes)

**Comment by christian-carey** [comment]
Hi @evvvritt. 
I was having issues cloning with the github desktop app
Screen Shot 2023-09-14 at 9 01 38 AM
, so I forked the repo on the github browser, copied the local changes I made in pages.svelte into the code editor in the github browser and committed from the browser UI and also initiated a pull request there. 
I can't find a way to update the commit message from the github browser,
Screen Shot 2023-09-14 at 8 53 12 AM
, and I'm not sure how to run npm check on the browser github repo.

Do you have any advice? :)

**Comment by christian-carey** [comment]
@evvvritt I added a commit with a message with the required formatting on top of the previous commit. Does that satisfy the requirements?

Also, would you mind sending me a screenshot of the unused CSS when running `npm run check` so I can remove it? 

I tried cloning again, but I seem to have an issue with the emojis in the filenames of the icons that causes an error, so I'm working from the github website.

Thank you for your patience. This is my first contribution to an open source project, and I am trying to learn my way through it.

**Comment by christian-carey** [comment]
Fair enough. I did try to clone from VSCode, but all attempts to checkout from git haven't worked. I looked into it more, and it seems to be a MacOS illegal byte sequence issue. I will try it again on windows.

**Comment by evvvritt** [comment]
Strange, I use MacOS + VS Code. Can you screenshot this byte sequence error please? It's probably these emoji-named files which we can rename

**Comment by christian-carey** [comment]
image
I believe it is the emoji-name files. I was able to successfully clone the repo on Windows through VSCode, so I'm working on setting up my dev environment there

**Comment by christian-carey** [comment]
I deleted the fork I made, remade it, and intend to reinitiate a PR once I get my windows dev env setup, the proper changes made + proper commit msg and an npm run check done.

**Comment by christian-carey** [comment]
Screen Shot 2023-09-21 at 4 02 58 PM

I had problems with windows npm, so I went back to mac. I am having issues with the emoji files

**Pull request closed without merging**
